CREATE TABLE IF NOT EXISTS "policies" (
    "_id"               INTEGER PRIMARY KEY,
    "policy_no"         INT,
    "familycode"        VARCHAR(15),
    "perscode"          VARCHAR(10),
    "issue_date"        TIMESTAMP,
    "comp_date"         TIMESTAMP,
    "payment_mode"      VARCHAR(5),
    "premium"           DECIMAL(15, 2),
    "sum_assured"       DECIMAL(15, 2),
    "plan"              INT,
    "term"              INT,
    "ppt"               INT,
    "next_premium"      TIMESTAMP,
    "mat_date"          TIMESTAMP,
    "mat_amount"        DECIMAL(15, 2),
    "pr_end_date"       TIMESTAMP,
    "loan"              INTEGER,
    "loan_dt"           TIMESTAMP,
    "tpremium"          DECIMAL(15, 2),
    "nominee"           VARCHAR(80),
    "relation"          VARCHAR(20),
    "agcode"            VARCHAR(15),
    "policy_updated"    TIMESTAMP,
    "stat_cd"           VARCHAR(180),
    "status"            VARCHAR(180),
    "fupstatus"         VARCHAR(50),
    "age"               INTEGER,
    "lastpaid"          TIMESTAMP,
    "neft"              VARCHAR(10),
    "nach"              VARCHAR(10),
    "sb_option"         INTEGER,
    "olife"             VARCHAR(4) DEFAULT 'N',
    "plan_name"         VARCHAR(255),
    "ann_mode"          VARCHAR(5),
    "ann_amount"        DECIMAL(15, 2),
    "lastfup"           TIMESTAMP,
    "velead_id"         VARCHAR(15),
    "branch"            VARCHAR(15),
    "tstamp"            VARCHAR(25),
    "dab"               INTEGER DEFAULT 0,
    "termrider"         INTEGER DEFAULT 0,
    "existing_policy"   INTEGER DEFAULT 0,
    "fup_updated"       VARCHAR(50),
    "custid"            VARCHAR(50),
    "final_mat_date"    TIMESTAMP,

    CONSTRAINT "fk_policies_family"
        FOREIGN KEY ("familycode") REFERENCES "family" ("familycode")
        ON DELETE CASCADE
);
