CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS "agent" (
    "_id"           SERIAL PRIMARY KEY,
    "name"          VARCHAR(80),
    "address"       VARCHAR(200),
    "mobile"        VARCHAR(80),
    "email"         VARCHAR(120),
    "company"       VARCHAR(150),
    "aboutus"       TEXT,
    "photo"         TEXT,
    "slogan"        VARCHAR(200),
    "login"         VARCHAR(20),
    "password"      VARCHAR(80),
    "website"       VARCHAR(100),
    "isprimary"     BOOLEAN DEFAULT FALSE,
    "autopass"      BOOLEAN DEFAULT FALSE,
    "dob"           TIMESTAMP,
    "userkey"       VARCHAR(255),
    "mpin"          VARCHAR(10),
    "newpassword"   VARCHAR(100),
    "ag_since"      TIMESTAMP,
    "branch"        VARCHAR(20),
    "club"          VARCHAR(25),
    "clia_id"       VARCHAR(20),
    "machine_id"    VARCHAR(100),
    "newuserkey"    TEXT,
    "login_mode"    VARCHAR(20),
    "marriagedate"  TIMESTAMP,
    "terminated"    BOOLEAN,
    "ren_dt"        TIMESTAMP,
    "licence_no"    VARCHAR(100),
    "intimation"    SMALLINT DEFAULT 1,
    "scheduling"    SMALLINT DEFAULT 1,
    "report"        SMALLINT DEFAULT 1,
    "authtoken"     TEXT,
    "authjson"      TEXT,
    "devicedata"    TEXT,
    "newpass"       VARCHAR(15),
    "devicename"    VARCHAR(50),
    "devicetoken"   VARCHAR(100),
    "newportal"     BOOLEAN DEFAULT FALSE,
    "pan"           VARCHAR(15)
);
