ALTER TABLE agent  ALTER COLUMN name DROP NOT NULL, ALTER COLUMN email DROP NOT NULL, ALTER COLUMN login DROP NOT NULL, ALTER COLUMN password DROP NOT NULL, ALTER COLUMN mobile DROP NOT NULL;
ALTER TABLE client ALTER COLUMN familycode DROP NOT NULL, ALTER COLUMN perscode DROP NOT NULL, ALTER COLUMN name DROP NOT NULL;
ALTER TABLE family ALTER COLUMN familycode DROP NOT NULL, ALTER COLUMN headname DROP NOT NULL;
